[project]
name = "bunkerbot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.30.0",
    "pytest>=9.1.1",
    "pytest-asyncio>=1.4.0",
    "python-dotenv>=1.2.2",
]

[tool.pytest.ini_options]
pythonpath = [
  "."
]

[tool.bandit]
exclude_dirs = [".venv", "tests"]
skips = [
    "B311", # Standard pseudo-random generators are not suitable for security/cryptographic purposes.
    "B110", # Try, Except, Pass detected.
]
