apiVersion: apps/v1
kind: Deployment
metadata:
  name: bunker-bot
  namespace: default
  labels:
    app: bunker-bot
status: {}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bunker-bot
  template:
    metadata:
      labels:
        app: bunker-bot
    spec:
      containers:
        - name: agent
          image: ghcr.io/piterpentester/bunker-bot:903e356c
          imagePullPolicy: IfNotPresent
          env:
            - name: TG_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: bunker-bot-secrets
                  key: TG_API_TOKEN
